# Generated by Django 2.1 on 2018-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': 'user_msg'},
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=500, verbose_name='msg_address'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(max_length=20, verbose_name='user'),
        ),
    ]
